#!/bin/bash

studyCycle=216000
studyBreak=600

function CountStudyCycle {
 for((time=0; time<studyCycle; time++))
  do
   sleep 1
  done

 notify-send "Break 10 min"
 CountBreakCycle
}


function CountBreakCycle {
 for((time=0; time<studyBreak; time++))
  do
   sleep 1
  done

 notify-send "Study 1h"
 CountStudyCycle
}


CountStudyCycle



